import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
}

export default function Home() {
  return (
    <>
      <h1 className="text-3xl">Hello Next.JS</h1>
      <p className="text-lg text-orange-400">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos similique totam minus placeat accusamus repellat in vitae minima earum ut beatae harum reiciendis quo nostrum voluptatem, ab quidem nemo dolorum.</p>
    </>
  )
}